POST http://127.0.0.1/files/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image";
Content-Type: text/plain

< ./testfile2.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--